name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o lmcmd lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-linux and capture output
        id: run_lmcmd
        run: ./lmcmd "find all files with file name starting with xx, starting from the root folder" | tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if grep -q "find /" output.log; then
            echo "String found in output"
          else
            echo "String not found"
            exit 1
          fi

      - name: Prepare Linux binary for upload
        if: steps.check_output.conclusion == 'success'
        run: |
          mkdir -p release/linux
          mv lmcmd release/linux/lmcmd

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-linux
          path: output.log

  build-macos-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for macOS x86
        run: |
          GOOS=darwin GOARCH=amd64 go build -v -o lmcmd lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-macos-x86 and capture output
        id: run_lmcmd
        run: ./lmcmd "find all files with file name starting with xx, starting from the root folder" | tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if grep -q "find /" output.log; then
            echo "String found in output"
          else
            echo "String not found"
            exit 1
          fi

      - name: Prepare macOS x86 binary for upload
        if: steps.check_output.conclusion == 'success'
        run: |
          mkdir -p release/macos-x86
          mv lmcmd release/macos-x86/lmcmd

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-macos-x86
          path: output.log

  build-macos-m1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for macOS M1
        run: |
          GOOS=darwin GOARCH=arm64 go build -v -o lmcmd lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-macos-m1 and capture output
        id: run_lmcmd
        run: ./lmcmd "find all files with file name starting with xx, starting from the root folder" | tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if grep -q "find /" output.log; then
            echo "String found in output"
          else
            echo "String not found"
            exit 1
          fi

      - name: Prepare macOS M1 binary for upload
        if: steps.check_output.conclusion == 'success'
        run: |
          mkdir -p release/macos-m1
          mv lmcmd release/macos-m1/lmcmd

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-macos-m1
          path: output.log

  release:
    needs: [build-linux, build-macos-x86, build-macos-m1]
    runs-on: ubuntu-latest
    if: needs.build-linux.result == 'success' && needs.build-macos-x86.result == 'success' && needs.build-macos-m1.result == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Read version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Tag version
        run: |
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux binary
        uses: actions/download-artifact@v3
        with:
          name: release-linux
          path: release/linux

      - name: Download macOS x86 binary
        uses: actions/download-artifact@v3
        with:
          name: release-macos-x86
          path: release/macos-x86

      - name: Download macOS M1 binary
        uses: actions/download-artifact@v3
        with:
          name: release-macos-m1
          path: release/macos-m1

      - name: Upload Linux binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/linux/lmcmd
          asset_name: linux/lmcmd
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS x86 binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/macos-x86/lmcmd
          asset_name: macos-x86/lmcmd
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS M1 binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/macos-m1/lmcmd
          asset_name: macos-m1/lmcmd
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
