name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o lmcmd-linux lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-linux and capture output
        id: run_lmcmd
        run: ./lmcmd-linux "find all files with file name starting with xx, starting from the root folder"| tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if cat output.log | grep "find /" 
          then
                  echo "String found in output"
          else 
                  echo "String not found"
                  exit 1
          fi

      - name: Upload Linux binary
        if: steps.check_output.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: lmcmd-linux-binary
          path: lmcmd-linux

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-linux
          path: output.log

  build-macos-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for macOS x86
        run: |
          GOOS=darwin GOARCH=amd64 go build -v -o lmcmd-macos-x86 lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-macos-x86 and capture output
        id: run_lmcmd
        run: ./lmcmd-macos-x86 "find all files with file name starting with xx, starting from the root folder" | tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if cat output.log | grep "find /" 
          then
                  echo "String found in output"
          else 
                  echo "String not found"
                  exit 1
          fi

      - name: Upload macOS x86 binary
        if: steps.check_output.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: lmcmd-macos-x86-binary
          path: lmcmd-macos-x86

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-macos-x86
          path: output.log

  build-macos-m1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build for macOS M1
        run: |
          GOOS=darwin GOARCH=arm64 go build -v -o lmcmd-macos-m1 lmcmd.go

      - name: Write API key to config
        run: |
          mkdir -p ~/.lmcmd
          echo "${{ secrets.API_KEY }}" > ~/.lmcmd.config

      - name: Run lmcmd-macos-m1 and capture output
        id: run_lmcmd
        run: ./lmcmd-macos-m1 "find all files with file name starting with xx, starting from the root folder" | tee output.log

      - name: Check output for specific string
        id: check_output
        run: |
          if cat output.log | grep "find /" 
          then
                  echo "String found in output"
          else 
                  echo "String not found"
                  exit 1
          fi

      - name: Upload macOS M1 binary
        if: steps.check_output.conclusion == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: lmcmd-macos-m1-binary
          path: lmcmd-macos-m1

      - name: Upload output log
        if: steps.check_output.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: output-log-macos-m1
          path: output.log

  release:
    needs: [build-linux, build-macos-x86, build-macos-m1]
    runs-on: ubuntu-latest
    if: needs.build-linux.result == 'success' && needs.build-macos-x86.result == 'success' && needs.build-macos-m1.result == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Read version
        id: get_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Tag version
        run: |
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create binary directory
        run: mkdir -p binary
      - name: Create Linux Directory
        run: mkdir -p binary/linux
      - name: Create macOS M1 Directory
        run: mkdir -p binary/macos-m1
      - name: Create macOS x86 Directory
        run: mkdir -p binary/macos-x86
      
      - name: Download Linux binary
        uses: actions/download-artifact@v3
        with:
          name: lmcmd-linux-binary
          path: binary/linux

      - name: Download macOS x86 binary
        uses: actions/download-artifact@v3
        with:
          name: lmcmd-macos-x86-binary
          path: binary/macos-x86

      - name: Download macOS M1 binary
        uses: actions/download-artifact@v3
        with:
          name: lmcmd-macos-m1-binary
          path: binary/macos-m1

      - name: Upload Linux binary to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binary
          asset_name: binary
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

